# Image: awbarnes/low_power_collectd
from centos:7.4.1708

RUN adduser apim
RUN yum clean all && yum -y update
RUN yum -y groupinstall development
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python36u
RUN yum -y install python36u-pip

ADD requirements.txt /requirements.txt
RUN pip3.6 install -r /requirements.txt

RUN yum -y install collectd

# gnocchi plugin requires pip2
RUN yum -y install python2-devel python-pip

# checkout and build the gnocchi plugin
RUN git clone https://github.com/ChameleonCloud/collectd-gnocchi.git
RUN cd /collectd-gnocchi && pip2 install .

# collectd.conf
ADD collectd.d/* /etc/collectd.d/

# exec script
ADD ironic_ids.json /ironic_ids.json
ADD collect_readings.py /collect_readings.py

ENTRYPOINT ["collectd", "-f"]
