# Image: awbarnes/dell_collectd
FROM centos:7.4.1708

RUN adduser apim
RUN yum clean all && yum -y update
RUN yum -y groupinstall development
RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python36u
RUN yum -y install python36u-pip
RUN yum -y install collectd
RUN yum -y install ipmitool


# gnocchi plugin requires pip2
RUN yum -y install python2-devel python-pip

# checkout and build the gnocchi plugin
RUN git clone https://github.com/ChameleonCloud/collectd-gnocchi.git
RUN cd /collectd-gnocchi && git checkout moonshot-power && pip2 install .

# collectd.conf
ADD collectd.conf /etc/collectd.conf

# exec script
ADD dell_nodes.json /dell_nodes.json
ADD collect_dell_readings.py /collect_dell_readings.py

ENTRYPOINT ["collectd", "-f"]
