version: "2.0"
services:
    lowPowerCollectd:
         image: jstubbs/low_power_collectd
         mounts:
             - ./low_power_conf.json:/low_power_conf.json
             - ./ssh_password:/ssh_password
             - ./collectd-gnocchi.conf.password:/etc/collectd.d//collectd-gnocchi.conf
         environment:
             HOSTNAME:
             INTERVAL:
