version: "2.0"
services:
    lowPowerCollectd:
         image: jstubbs/low_power_collectd
         privileged: True
         volumes:
             - ./low_power_conf.json:/low_power_conf.json
             - ./ssh_password:/ssh_password
             - ./collectd-gnocchi.conf.password:/etc/collectd.conf
             - ./data:/var/lib/collectd/
         environment:
             HOSTNAME:
             INTERVAL:
